# Generated by Django 3.2.2 on 2021-05-23 01:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Faixa Etária',
                'verbose_name_plural': 'Faixa Etária',
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'designer',
                'verbose_name_plural': 'designer',
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Adicionar Gênero',
                'verbose_name_plural': 'Adicionar Gêneros',
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='Graphics_Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Motor Gráfico',
                'verbose_name_plural': 'Motor Gráfico',
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='MinimumRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Requisitos Minimos',
                'verbose_name_plural': 'Requisitos Minimos',
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='Operational_System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Adicionar Sistema Operacional',
                'verbose_name_plural': 'Adicionar Sistema Operacional',
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Número de Jogadores',
                'verbose_name_plural': 'Número de Jogadores',
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Adicionar Editora',
                'verbose_name_plural': 'Adicionar Editora',
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Requisitos Recomendados',
                'verbose_name_plural': 'Requisitos Recomendados',
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='Select_Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Adicionar Linguagem',
                'verbose_name_plural': 'Adicionar Linguagem',
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Título do jogo')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='general_post', verbose_name='Imagem')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('disponivel', 'Disponivel'), ('indisponivel', 'Indisponivel')], default='disponivel', max_length=15, null=True)),
                ('published', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Publicado')),
                ('servant', models.DateTimeField(auto_now_add=True, null=True)),
                ('Changed', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Valor')),
                ('Operational_System', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_post.operational_system', verbose_name='Sistema Operacional')),
                ('Select_Language', models.ManyToManyField(blank=True, null=True, related_name='get_posts', to='general_post.Select_Language', verbose_name='Linguagens')),
                ('age_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_post.age_range', verbose_name='Faixa Etária')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('designer', models.ManyToManyField(blank=True, null=True, related_name='get_posts', to='general_post.Designer', verbose_name='Projetista')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_post.gamecategory', verbose_name='Gênero')),
                ('graphics_engine', models.ManyToManyField(blank=True, null=True, related_name='get_posts', to='general_post.Graphics_Engine', verbose_name='Motor Gráfico')),
                ('minimum_requirements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_post.minimumrequirements', verbose_name='Requisitos Minimos')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_post.player', verbose_name='Número de Jogadores')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_post.publisher', verbose_name='Editora')),
                ('recommended_requirements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_post.recommendedrequirements', verbose_name='Requisitos Recomendados')),
            ],
            options={
                'verbose_name': 'Adicionar Jogo',
                'verbose_name_plural': 'Adicionar Jogos',
            },
        ),
    ]
