# Generated by Django 3.2 on 2021-04-20 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Título do jogo')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor')),
                ('image', models.ImageField(null=True, upload_to='general_post', verbose_name='Imagem')),
                ('status', models.CharField(choices=[('disponivel', 'Disponivel'), ('indisponivel', 'Indisponivel')], default='disponível', max_length=15, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
    ]
