# Generated by Django 3.2 on 2021-04-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_post', '0002_remove_post_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Valor'),
        ),
    ]
