# Generated by Django 3.2 on 2021-04-23 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_post', '0002_remove_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecategory',
            options={'ordering': ['-servant'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
