# Generated by Django 3.2 on 2021-04-25 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general_post', '0003_auto_20210425_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operational_System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('servant', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Adicionar Sistema Operacional',
                'verbose_name_plural': 'Adicionar Sistema Operacional',
                'ordering': ['-servant'],
            },
        ),
        migrations.CreateModel(
            name='Select_Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('servant', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Adicionar Linguagem',
                'verbose_name_plural': 'Adicionar Linguagem',
                'ordering': ['-servant'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='Operational_System',
            field=models.ManyToManyField(null=True, related_name='get_posts', to='general_post.Operational_System', verbose_name='Sistema Operacional'),
        ),
        migrations.AddField(
            model_name='post',
            name='Select_Language',
            field=models.ManyToManyField(null=True, related_name='get_posts', to='general_post.Select_Language', verbose_name='Linguagens'),
        ),
    ]
