# Generated by Django 3.2 on 2021-04-20 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_post', '0003_post_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='valor',
            new_name='value',
        ),
    ]
