# Generated by Django 3.2 on 2021-04-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_post', '0003_alter_gamecategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(null=True, related_name='get_posts', to='general_post.GameCategory', verbose_name='Categoria dos jogos'),
        ),
    ]
