# Generated by Django 3.2 on 2021-04-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_post', '0004_rename_valor_post_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='Descrição'),
        ),
    ]
