# Generated by Django 3.2 on 2021-04-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_post', '0004_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecategory',
            options={'ordering': ['-servant'], 'verbose_name': 'Adicionar Gênero', 'verbose_name_plural': 'Adicionar Gêneros'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Adicionar Jogo', 'verbose_name_plural': 'Adicionar Jogos'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ManyToManyField(null=True, related_name='get_posts', to='general_post.GameCategory', verbose_name='Gênero'),
        ),
    ]
