# Generated by Django 3.2 on 2021-05-04 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general_post', '0004_auto_20210425_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='age_range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('servant', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Faixa Etária',
                'verbose_name_plural': 'Faixa Etária',
                'ordering': ['-servant'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='age_range',
            field=models.ManyToManyField(null=True, related_name='get_posts', to='general_post.age_range', verbose_name='Faixa Etária'),
        ),
    ]
