# Generated by Django 3.2 on 2021-05-04 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_post', '0005_auto_20210504_0449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='age_range',
            old_name='name',
            new_name='age',
        ),
    ]
