# Generated by Django 3.2 on 2021-05-04 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_post', '0006_rename_name_age_range_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='age_range',
            old_name='age',
            new_name='name',
        ),
    ]
