# Generated by Django 3.2 on 2021-05-05 03:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general_post', '0008_rename_name_age_range_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'designer',
                'verbose_name_plural': 'designer',
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='Graphics_Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Motor Gráfico',
                'verbose_name_plural': 'Motor Gráfico',
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='MinimumRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Requisitos Minimos',
                'verbose_name_plural': 'Requisitos Minimos',
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Número de Jogadores',
                'verbose_name_plural': 'Adicionar Linguagem',
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Requisitos Recomendados',
                'verbose_name_plural': 'Requisitos Recomendados',
                'ordering': ['-create'],
            },
        ),
        migrations.AlterModelOptions(
            name='age_range',
            options={'ordering': ['-create'], 'verbose_name': 'Faixa Etária', 'verbose_name_plural': 'Faixa Etária'},
        ),
        migrations.AlterModelOptions(
            name='gamecategory',
            options={'ordering': ['-create'], 'verbose_name': 'Adicionar Gênero', 'verbose_name_plural': 'Adicionar Gêneros'},
        ),
        migrations.AlterModelOptions(
            name='operational_system',
            options={'ordering': ['-create'], 'verbose_name': 'Adicionar Sistema Operacional', 'verbose_name_plural': 'Adicionar Sistema Operacional'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['-create'], 'verbose_name': 'Adicionar Editora', 'verbose_name_plural': 'Adicionar Editora'},
        ),
        migrations.AlterModelOptions(
            name='select_language',
            options={'ordering': ['-create'], 'verbose_name': 'Adicionar Linguagem', 'verbose_name_plural': 'Adicionar Linguagem'},
        ),
        migrations.RenameField(
            model_name='age_range',
            old_name='servant',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='gamecategory',
            old_name='servant',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='operational_system',
            old_name='servant',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='servant',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='select_language',
            old_name='servant',
            new_name='create',
        ),
        migrations.AlterField(
            model_name='post',
            name='age_range',
            field=models.ManyToManyField(null=True, related_name='get_posts', to='general_post.Age_Range', verbose_name='Faixa Etária'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publisher',
            field=models.ManyToManyField(null=True, related_name='get_posts', to='general_post.Publisher', verbose_name='Editora'),
        ),
        migrations.AddField(
            model_name='post',
            name='designer',
            field=models.ManyToManyField(null=True, related_name='get_posts', to='general_post.Designer', verbose_name='Projetista'),
        ),
        migrations.AddField(
            model_name='post',
            name='graphics_engine',
            field=models.ManyToManyField(null=True, related_name='get_posts', to='general_post.Graphics_Engine', verbose_name='Motor Gráfico'),
        ),
        migrations.AddField(
            model_name='post',
            name='minimum_requirements',
            field=models.ManyToManyField(null=True, related_name='get_posts', to='general_post.MinimumRequirements', verbose_name='Requisitos Minimos'),
        ),
        migrations.AddField(
            model_name='post',
            name='player',
            field=models.ManyToManyField(null=True, related_name='get_posts', to='general_post.Player', verbose_name='Número de Jogadores'),
        ),
        migrations.AddField(
            model_name='post',
            name='recommended_requirements',
            field=models.ManyToManyField(null=True, related_name='get_posts', to='general_post.RecommendedRequirements', verbose_name='Requisitos Recomendados'),
        ),
    ]
