# Generated by Django 3.2.2 on 2021-05-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_post', '0011_auto_20210507_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='age_range',
            field=models.ManyToManyField(null=True, related_name='get_posts', to='general_post.Age_Range', verbose_name='Faixa Etária'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publisher',
            field=models.ManyToManyField(null=True, related_name='get_posts', to='general_post.Publisher', verbose_name='Editora'),
        ),
    ]
