# Generated by Django 3.2.2 on 2021-05-10 01:41

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general_post', '0013_auto_20210508_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Operational_System',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_posts', to='general_post.Operational_System', verbose_name='Sistema Operacional'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Select_Language',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_posts', to='general_post.Select_Language', verbose_name='Linguagens'),
        ),
        migrations.AlterField(
            model_name='post',
            name='age_range',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_posts', to='general_post.Age_Range', verbose_name='Faixa Etária'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='post',
            name='designer',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_posts', to='general_post.Designer', verbose_name='Projetista'),
        ),
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_posts', to='general_post.GameCategory', verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='post',
            name='graphics_engine',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_posts', to='general_post.Graphics_Engine', verbose_name='Motor Gráfico'),
        ),
        migrations.AlterField(
            model_name='post',
            name='minimum_requirements',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_posts', to='general_post.MinimumRequirements', verbose_name='Requisitos Minimos'),
        ),
        migrations.AlterField(
            model_name='post',
            name='player',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_posts', to='general_post.Player', verbose_name='Número de Jogadores'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publisher',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_posts', to='general_post.Publisher', verbose_name='Editora'),
        ),
        migrations.AlterField(
            model_name='post',
            name='recommended_requirements',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_posts', to='general_post.RecommendedRequirements', verbose_name='Requisitos Recomendados'),
        ),
        migrations.AlterField(
            model_name='post',
            name='servant',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
